export const profile = {
 name: 'Sanskriti Binani', email: 'sanskriti.binani11@gmail.com',
 github: 'https://github.com/Sanskriti1110', linkedin: 'https://www.linkedin.com/in/sanskriti-binani/',
};
export const projects = [
 {id:'jonah',number:'01',name:'Jonah V4',category:'SENSOR HARDWARE / RAINMAKER TECHNOLOGIES',headline:'A faster response starts with the board.',summary:'An airborne pressure, temperature, and humidity sensor redesigned around thermal mass, a capacitive sensing front end, and the realities of calibration.',tags:['Altium Designer','Rigid-flex PCB','Sensor front end','Environmental testing'],image:'jonah-cutout.webp',alt:'Supplied Altium render of the Jonah V4 sensor board',caption:'JONAH V4 / SUPPLIED BOARD RENDER',role:'Sensor-board redesign, calibration & validation',sections:[{title:'The problem',text:'The previous humidity sensor responded in 2–4 seconds. For a moving airborne platform, sensor lag obscures changes in the surrounding air.'},{title:'The decision',text:'Move the temperature sensor onto a low-mass flex tail. Replace the sealed humidity sensor with an HMC07M capacitive element and PCAP04 readout, taking ownership of the analog signal chain.'},{title:'The implementation',text:'A four-layer rigid-flex board integrates temperature, pressure, and humidity sensing. A separate controller handles power conversion, acquisition, and the aspiration fan.'},{title:'The evidence',text:'The résumé reports a sub-second τ63 response and per-unit environmental-chamber calibration of five boards. The supplied comparison plot shows the sensor alongside the previous logger and an iMet reference.'}],result:'<1 s',resultLabel:'τ63 response reported in résumé',lesson:'Sensor placement, substrate, and thermal coupling are part of the measurement system.',evidence:'validation.webp',evidenceAlt:'Supplied temperature and humidity validation plot comparing Jonah sensor responses',evidenceCaption:'Original validation plot • supplied test record',note:'Controller revision B: bring-up results are still pending in the supplied presentation. Efficiency targets are not presented as measurements.'},
 {id:'foldeasy',number:'02',name:'FoldEasy',category:'CONNECTED HARDWARE / UPENN TEAM PROJECT',headline:'From a custom PCB to a physical action.',summary:'An automated clothes-folding machine that connects sensing, servo motion, fragrance misting, and remote control in one embedded system.',tags:['SAMW25','4-layer PCB','FreeRTOS','MQTT / Node-RED'],image:'foldeasy-system-cutout.webp',alt:'FoldEasy assembled folding platform and electronics',caption:'FOLDEASY / PHYSICAL PROTOTYPE',role:'PCB architecture, embedded firmware & IoT integration',sections:[{title:'The problem',text:'Translate the repetitive sequence of folding clothes into a sensor-triggered mechanism with local and remote control.'},{title:'The architecture',text:'The SAMW25 controls PWM servos, light and IR sensing, and an atomizer. USB-C input, a Li-ion power system, and DC-DC regulation support the custom four-layer board.'},{title:'The firmware',text:'FreeRTOS tasks coordinate sensing, actuation, and Wi-Fi. Semaphore-protected resources, a CLI, and an OTA bootloader support operation and debugging. MQTT sends system health to a Node-RED dashboard.'},{title:'The bench reality',text:'The team report documents a 2.2 A power design limited to 1.5 A on the manufactured prototype. Only one of three boards functioned correctly. Folding sequences were adapted to the available current.'}],result:'30 s',resultLabel:'System-health publication interval',lesson:'Test actuator current under real load before treating a power budget as closed.',evidence:'foldeasy-thermal.webp',evidenceAlt:'Thermal-camera image of FoldEasy PCB under load',evidenceCaption:'PCB under load • supplied thermal image',link:'https://github.com/ese5160/a14g-final-submission-s25-t25-foldeasy',credit:'Team: Sanskriti Binani and Chirag Satapathy.'},
 {id:'filterfox',number:'03',name:'FilterFox',category:'WIRELESS HARDWARE / FILTERFOX INC.',headline:'The whole signal path. Owned end to end.',summary:'ESP32-based IoT hardware spanning schematic capture, PCB layout, RF communication, power management, and system bring-up.',tags:['ESP32','LoRa · 915 MHz','Wi-Fi · 2.4 GHz','Altium Designer'],image:'filterfox-cutout.webp',alt:'Supplied FilterFox PCB image showing its components and routing',caption:'FILTERFOX / BOARD OVERVIEW',role:'Electrical integration, PCB design & system bring-up',sections:[{title:'The challenge',text:'Integrate sensing, dual wireless communication, and power control while preserving a buildable and testable PCB.'},{title:'The hardware',text:'The supplied transmitter and receiver projects include Altium schematics, board layouts, assembly documents, and fabrication outputs. The résumé describes LoRa and Wi-Fi RF routing and antenna matching.'},{title:'The power strategy',text:'An event-driven wake scheme reduced unnecessary active time. The résumé reports a 65–70% battery-life improvement; a supporting measurement log was not included.'},{title:'The manufacturing handoff',text:'Design reviews with PCB vendors and component-inventory coordination supported prototyping and system bring-up.'}],result:'915 MHz',resultLabel:'LoRa alongside 2.4 GHz Wi-Fi',lesson:'Wireless performance depends on the board, power state, and firmware behaving as one system.'},
 {id:'refresh',number:'04',name:'R.E.F.R.E.S.H.',category:'WEARABLE SYSTEMS / UPENN TEAM PROJECT',headline:'Sense. Decide. Cool.',summary:'A wearable cooling-glove prototype that joins physiological sensing, a PWM cooling loop, and connected telemetry.',tags:['ATmega328PB','ADC / I²C','ESP32 / Blynk','C / Python'],image:'refresh-cutout.webp',alt:'Physical R.E.F.R.E.S.H. glove prototype with fan, wiring and sensors',caption:'R.E.F.R.E.S.H. / BUILT GLOVE PROTOTYPE',role:'Sensor integration, cooling control & telemetry',sections:[{title:'The motivation',text:'Explore wearable sensing and active cooling for the demanding environment of motorsport.'},{title:'The implementation',text:'GSR and optical pulse sensing feed the embedded system through ADC and I²C. A PWM-controlled cooling loop responds to sensor input.'},{title:'The connected system',text:'The supplied implementation includes ATmega firmware, an ESP32-to-Blynk link, and Python processing. This portfolio describes that implemented path; LoRa appears in the earlier proposal.'},{title:'What is established',text:'The physical glove, firmware, and demonstration photos establish the prototype. The supplied report does not contain a completed quantitative validation section.'}],result:'ADC → PWM',resultLabel:'Sensor input to cooling control',lesson:'Keep a working prototype, a proposed capability, and a validated result clearly distinct.',link:'https://sanskriti1110.github.io/Team20_REFRESH/',credit:'Team: Sanskriti Binani, Chirag Satapathy, and Megha Mistry.'},
];
export const experience = [
 {date:'JUN 2026 — PRESENT',company:'Rainmaker Technologies',title:'Electrical Engineer Intern',text:'Rigid-flex airborne sensing, chamber calibration, and a custom relay-matrix motor test bench with four-wire Kelvin measurement.'},
 {date:'JAN — MAY 2026',company:'University of Pennsylvania',title:'Teaching Assistant · IoT Edge Computing',text:'Hardware bring-up, wireless and firmware debugging, and validation guidance for student project teams.'},
 {date:'MAY — DEC 2025',company:'FilterFox Inc.',title:'Hardware Engineering Intern',text:'ESP32 product integration, RF and power design, PCB layout, and manufacturing coordination.'},
 {date:'JAN — AUG 2025',company:'GRASP Robotics Lab · UPenn',title:'Researcher',text:'Four-layer EPC901 image-sensor breakout and nRF54L15 firmware with timer-triggered SAADC, DPPI, and double-buffered sampling.'},
];

// Bibliographic details verified against the supplied Google Scholar profile.
export const scholarProfile='https://scholar.google.com/citations?user=8NkIH0QAAAAJ&hl=en';
export const publications=[
 {year:'2024',title:'Recontextualizing the apartment complexes with a unified smart RFID card',authors:['Chirag Satapathy','Sanskriti Binani','R. Raja Singh'],venue:'AIP Conference Proceedings',reference:'Volume 2966 · Issue 1 · Article 020014',url:'https://pubs.aip.org/aip/acp/article-abstract/2966/1/020014/3279446'},
 {year:'2023',title:'Automated classification of pathological types of lung cancer-a machine learning approach',authors:['Sanskriti Binani','Chirag Satapathy'],venue:'IEEE · CIISCA 2023',reference:'International Conference on Computational Intelligence for Information, Security and Communication Applications · pp. 178–183',url:'https://ieeexplore.ieee.org/abstract/document/10403581/'}
];
